# Generated by Django 3.2.16 on 2023-06-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_name_measurement',
        ),
    ]
