# Generated by Django 3.2.16 on 2023-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230613_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.Recipe_ingredients', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
